version: 2

# Configuration: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: '[TASK]'
    labels:
      - dependencies
    open-pull-requests-limit: 10

  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: '[TASK]'
    labels:
      - dependencies
    open-pull-requests-limit: 10
    versioning-strategy: widen
